### ISSUE TITLE
Crash while loading ATM7 Sky world - Interaction with LaserIO

### ISSUE THREAD

**Issue by CZEMacLeod** [al132mc/alchemistry#254]
After updating the pack to ATM7 Sky 1.1.2 and trying to launch my world, I get a crash (attached)
[crash-2022-10-21_19.15.03-server.txt](https://github.com/SmashingMods/Alchemistry/files/9841524/crash-2022-10-21_19.15.03-server.txt)
This looks like it is crashing in com.smashingmods.alchemistry.api.storage.AutomationSlotHandler (probably a dissolver) being fed by hopper but extracted by LaserIO.
I can raise an issue on LaserIO, but I am not sure if the issue is there or here.
For reference the version of alchemisty is 1.18.2-2.10 (and there is also chemlib-1.18.2-2.0.11 in the pack but I don't know if that matters). laserio is 1.4.3

**Comment by jeremiahwinsley** [comment]
Got another report of this issue from a player: https://pastebin.com/udMDh9kX, with pipez this time

**Comment by Dark-Arcana** [comment]
Thank you all for the reports. I've been away for the weekend attending a friend's memorial service. I will make sure to fix this as soon as I am able and push it out asap. The last update made so many changes, that I was worried something like this would happen. We tested it pretty thoroughly, but not with any other mods. Whoops!

**Comment by Dark-Arcana** [comment]
Ok so from the looks of it, the only thing I can even imagine to be the cause is https://github.com/SmashingMods/Alchemistry/blame/1.18.x/src/main/java/com/smashingmods/alchemistry/common/block/dissolver/DissolverMenu.java#L23 . I changed the dissolver's output slot count from 10 to 12.

**Comment by Dark-Arcana** [comment]
Should be fixed in 497dd6a8a3fc98c98b7e9500d1fc78c14adcb033 though I wasn't able to replicate it. I'm pushing an update to CurseForge, so let me know if you run into this again.

**Comment by JakeMoe** [comment]
I'm getting the error in ATM7: To The Sky (that's my bug report linked above).  I've replaced both client and server with alchemistry-1.18.2-2.1.2.jar, but the error still occurred server-side.  Excerpt below, see attached crash report for details.

```
Time: 10/24/22, 10:23 AM
Description: Ticking block entity

java.lang.RuntimeException: Slot 11 not in valid range - [0,10)
        at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:207) ~[forge-1.18.2-40.1.80-universal.jar%23265!/:?] {re:classloading}
        at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:59) ~[forge-1.18.2-40.1.80-universal.jar%23265!/:?] {re:classloading}
        at com.smashingmods.alchemistry.api.storage.AutomationSlotHandler.getStackInSlot(AutomationSlotHandler.java:22) ~[alchemistry-1.18.2-2.1.2.jar%2344!/:1.18.2-2.1.2] {re:classloading}
        at com.smashingmods.alchemistry.api.blockentity.processing.AbstractInventoryBlockEntity$2.extractItem(AbstractInventoryBlockEntity.java:72) ~[alchemistry-1.18.2-2.1.2.jar%2344!/:1.18.2-2.1.2] {re:class loading}
```

[crash-2022-10-24_10.23.32-server.txt](https://github.com/SmashingMods/Alchemistry/files/9850907/crash-2022-10-24_10.23.32-server.txt)

**Comment by Dark-Arcana** [comment]
Have you tried breaking the dissolver and replacing it?

**Comment by bribri69** [comment]
Hello,

I have the same problem with a custom modpack (with pipez)
"java.lang.RuntimeException: Slot 10 not in valid range - [0,10)" :[crash-2022-10-24_19.50.03-server.txt](https://github.com/SmashingMods/Alchemistry/files/9854066/crash-2022-10-24_19.50.03-server.txt)

I'll try to break all the dissolvers in our world before update to the last version but it's a hard work when there's a lot of player that use alchemistry.

**Comment by bribri69** [comment]
There's a real problem with pipez and the dissolver... 
With alchemistry 2.0.9 I unplugged all the item pipes connected to dissolvers.
Then, i upgraded to 2.1.2 and i plugged an item pipez -> direct crash !
Rollback to 2.0.9 and unplug it again. Then I upgraded to 2.1.2 and i broke the dissolvers... And they don't dropped... they just disappeared oO
very weird and the energy pipe seemed still connected even there wasn't any block connected...
Finally i broke all the pipez and remade my setup and it finally work with Pipez !!
Unfortunately a friend extract items from the dissolver with Xnet... And it crashed again :
"Details:
	Name: xnet:controller // mcjty.xnet.modules.controller.blocks.TileEntityController
	Block: Block{xnet:controller}[error=false,facing=north]
	Block location: World: (1558,63,3),"
[crash-2022-10-24_22.20.45-server.txt](https://github.com/SmashingMods/Alchemistry/files/9855097/crash-2022-10-24_22.20.45-server.txt)

**Comment by Dark-Arcana** [comment]
Sounds like a caching issue of some kind. The only possible thing that can cause this was already fixed. However, you might need to break all of the blocks and replace them. Wonder if the block entities aren't being removed from the world when the block is being removed. That happens sometimes. If that's the case, place a chest or something where your dissolver was and then remove it.

**Comment by JakeMoe** [comment]
From v2.0.9, I've picked up the dissolver and popped it in a backpack.  I then shutdown the server and upgraded both client and server to v2.1.2, and started the server; it loaded fine.  I logged into the server and placed the dissolver back down in a different spot so it wasn't attached to the Mekanism Ultimate Logistical Transporter, and everything seemed fine.  I then picked it up again and put it back where it was against the Mek pipe and still had no issue.  So I logged out and shutdown the server, then started it fresh again.  All seems fine now on v2.1.2.

**Comment by Dark-Arcana** [comment]
Ok thank you so much for this testing. I think that the issue is that something is being cached somewhere in the world. So even if I fixed it, it still breaks until you move it. But this at least helps to confirm that it should be fixed.

**Comment by Dark-Arcana** [comment]
This should be confirmed fixed, update coming out today. Only re-open if you can confirm it's the same issue and if you remove the dissolver (and place some other block entity in its place) first.
